name: Waka Readme

on:
  schedule:
    - cron: "0 0 * * 1" # every Monday
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_PAT }}

          SHOW_TIMEZONE: false
          SHOW_TOTAL: true
          SHOW_PROFILE_VIEWS: true
          SHOW_EDITORS: true
          SHOW_PROJECTS: true

          SHOW_OS: true
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_LOC_CHART: false

          SHOW_LANGUAGE: false
          SHOW_LINES_OF_CODE: true
          SHOW_REPOS: false

          SHOW_SHORT_INFO: false

